name: Fix
description: 기능상 발견한 오류를 수정합니다.
title: "[Fix] "
labels: [fix]
body:
  - type: textarea
    attributes:
      label: 🐛 버그 설명
      description: 어떤 문제가 발생했는지 간단히 설명해주세요.
      placeholder: 예) 회원가입 버튼을 눌러도 동작하지 않음

  - type: textarea
    attributes:
      label: 📝 참고 사항
      description: API 명세서, 디자인, 기타 참고 링크가 있다면 적어주세요.
